---
name: CI

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get latest CasePro version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: rapidpro/casepro
          prefix: 'v'
        id: casepro_version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            onaio/casepro:latest
            onaio/casepro:${{ steps.casepro_version.outputs.tag }}
          build-args: |
            CASEPRO_VERSION=${{ steps.casepro_version.outputs.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
